# Generated by Django 4.2.5 on 2023-09-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='<i class="fa-solid fa-dollar-sign" style="color: #8fa9d6;"></i>', max_length=200),
            preserve_default=False,
        ),
    ]
