# Generated by Django 4.2.5 on 2023-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-dollar-sign', max_length=200),
        ),
    ]
