# Generated by Django 4.2.5 on 2023-09-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='rgba(255, 99, 132, 0.7)', max_length=50),
        ),
    ]
